[package]
name = "wasm-bindgen"
version = "0.2.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
categories = ["wasm"]
repository = "https://github.com/alexcrichton/wasm-bindgen"
homepage = "https://github.com/alexcrichton/wasm-bindgen"
documentation = "https://docs.rs/wasm-bindgen"
description = """
Easy support for interacting between JS and Rust.
"""

[lib]
test = false
doctest = false

[dependencies]
wasm-bindgen-macro = { path = "crates/macro", version = "0.2" }

[dev-dependencies]
test-support = { path = "crates/test-support" }

[workspace]
members = [
  "crates/cli",
  "examples/hello_world",
  "examples/smorgasboard",
  "examples/console_log",
  "examples/dom",
  "examples/math",
  "examples/performance",
  "examples/wasm-in-wasm",
]

[profile.release]
lto = true
opt-level = 'z'
panic = 'abort'
